### ISSUE TITLE
Roadmap 7.2.0

### ISSUE THREAD

**Issue by kangarko** [kangarko/ChatControl-Pro#141]
This is an continuously updated list of features to be considered and added in the 7.2.0 release. 
Sidenote: Those are no promises.

# NB! This release is closed for suggestions.

## Normal priority
- [x] Notify player that nobody will see their message in ranged chat.
- [x] Notify player when PMing an afk player.
- [x] Wait before typing messages on join. 
- [x] Party chat channels for Towny and Factions
- [x] Rewrite YAML files so they make more sense to new users.

## Delayed
- Rewrite formatter to display player's message differently for each player online. This makes a) faction relation color placeholder and b) /ignore command possible.
- {recipient} placeholder #68
- /togglepm with MySQL support

## Trashed
- Make private messages ignore vanished players _Too many different vanish plugins & time lack._
- FactionsUUID (1.6.x) support. _Just use PlaceholderAPI_

**Feel free to comment below, but comments are cleaned regularly to keep this page clean.**

**Comment by c0wg0d** [comment]
Does the "{recipient} placeholder" have anything to do with spying commands or is that just for the private message formatter?  I would really like to be able to format spied commands so I can see who someone is sending PM's to.

**Comment by Bobobaal** [comment]
Is it somewhat possible to add some sort of multi-prefix support for chat formatting just like chatex has?

**Comment by kangarko** [comment]
@c0wg0d It is only for PM's, but in spying, you see the entire command, so you see who's the receiver.

@Bobobaal  There already is multi prefix/suffix support. Check Variables.Vault section in setting.yml

**Comment by c0wg0d** [comment]
You don't if they are using /r or /reply though.  This is why I wish spying had two options, one for spying messages and one for spying all other commands.  I realize this is out of scope for this release, but that is how VentureChat does it and it's quite nice.  For PM's, moderators see:

[player1->player2] This is a PM from player1 to player2.  Hi.

And for commands, they see:

player1: /op player1

The formats are completely separate based on their function.

What would be nice in ChatControl's case would be to have a separate "Parts" section in Private_Message_Receiver in chat.yml that is only for admins, which formats a private message appropriately for anyone with /spy toggled on.

**Comment by kangarko** [comment]
I see. I don't know about the parts, but when I will be adding recipient placeholder I will look into PMs to get them make more sense for spying.

**Comment by kangarko** [comment]
Development is nearly completed. Expect a release tonight.

**Comment by kangarko** [comment]
Released.
