### ISSUE TITLE
🎈 Roadmap 7.3.0

### ISSUE THREAD

**Issue by kangarko** [kangarko/ChatControl-Pro#163]
This is an continuously updated list of features to be **considered** and added in the 7.3.0 release. 
Sidenote: Those are no promises.

# NB! When suggesting a feature, keep in mind this is a plugin for your chat.
## Top priority
- [x] Prevent commands from signs and books (+ check Wurst and see the different options, also for potions (?))
- [x] Discord and https://github.com/Speentie8081/HardScene_Bukkit-API integration
- [ ] /tell: Fix https://www.spigotmc.org/threads/%E2%99%A3-chatcontrol-pro-paid.82298/page-115#post-2310182
- [x] Include MvDW placeholder support
- [ ] bungee: Players on other servers can't see players in a channel from other servers
- [ ] /tell: Add support for vanished players
- [x] DynMap and discordSRV integration for (json) chat formatter
- [x] Share warning points over Bungee
- [ ] MySQL: Storing chat logs 
- [ ] /tell: Partial username matches in /tell (example: instead of /msg PlayerName, only /msg play is sufficient and the player will be found)
- [ ] Anti-spam: Limit amount of messages or commands sent per time unit

## High priority
- [ ] Better yaml comments in chat.yml and messages.yml
- [x] Revert support for Minecraft 1.7.10 and older 
- [ ] BungeeControlBridge bungee fake join/kick messages
- [ ] An option to toggle sound notify _Maybe create an UI with more options ?_

## Normal priority
- [ ] Rewrite formatter to display player's message differently for each player online. This makes a) faction relation color placeholder and b) /ignore command possible.
    - [x] {recipient} placeholder #68
    - [ ] {sender-server} and {recipient-server}
- [ ] customizable format in /spy
- [ ] /togglepm with MySQL support
- [ ] Mute a channel and bypass with permission
- [ ] Channel system: spies are seen in player list
- [ ] Centering message in motd
- [ ] Mail system (?)

## Trashed
- Hardcode DeluxeChat compatibiltiy ? https://www.spigotmc.org/threads/%E2%99%A3-chatcontrol-pro-paid.82298/page-115#post-2310100 _Compatible using custom listener priorities of Formatter._

**Feel free to comment below, but comments are cleaned regularly to keep this page clean.**

**Comment by brickman312** [comment]
I am not sure if my post I made yesterday was deleted or not, but I had mentioned the current system in which you can change/switch channels. Essentially I just suggested that when you ran the /ch switch command, it would switch to the channel regardless if you were spying or not. (Currently you can not switch to a channel you are spying on).

**Comment by kangarko** [comment]
I remember your post and I wrote that this is totally possible, but in the meanwhile I have other stuff that take priority. I gladly take that as a suggestion to the future and get to it when I prepare some other changes in channel system which I believe are even more welcome.

**Comment by brickman312** [comment]
Okay, thank you for responding and sorry for the repost. I did not see your previous response and was confused why mine was suddenly deleted.

**Comment by Curtis73** [comment]
Hey,
Would it be possible to add a command that would mute a channel (/ch mute) and only those with certain permissions would be able to speak?
Thanks!

**Comment by kangarko** [comment]
Hey, I have asserted that as a suggestion, thanks!

**Comment by AndGK** [comment]
Hey, I would like to see /ignore just like essentials have but for ChatControl messages and chat :)

**Comment by kangarko** [comment]
The /ignore is planned in the future 8.0.0 roadmap.

**Comment by SamariStorm** [comment]
Hey would it be possible to add an option for which channel message notification sounds are played through in minecraft? It would be great if we could use the Voice/Speech channel so that players can adjust the volume / mute notification sounds if they don't like them without having to sacrifice the whole games sound from master. Just a thought :)

**Comment by kangarko** [comment]
Hey, what kind of notification sounds are you thinking of?

**Comment by SamariStorm** [comment]
I currently have a server setup with noises on join, @player and when an announcement is made. Which is great! But I want to change which source channel they are played through, like using the full command "/playsound [sound name] **[source]** [player] [x] [y] [z] [volume] [pitch] [minimum volume]". Currently the source default is Master (Tested by muting every sound channel but Master) but I would really love to send it through the Voice/Speech channel so that players can mute that channel if they don't want to hear notifications but don't want to turn off all the game sounds from muting master.

I think currently there's only access to [sound name] [volume] and [pitch] which works really well don't get we wrong, this would just be a nice addition for people who are super picky ^^;

Just wondering if this is a possibility at all? Completely fine if it's not :D

**Comment by kangarko** [comment]
Hey, yes, I believe it is totally possible, not with just the current system. I take that as a future suggestion however :)

**Comment by Porama6400** [comment]
" Storing chat logs in MySQL" is in NORMAL priority?

Don't you think it's important?

**Comment by kangarko** [comment]
Yes I see the possibilities it opens. I have moved it up.

**Comment by kangarko** [comment]
Closing, see https://github.com/kangarko/ChatControl-Pro/issues/267
