### ISSUE TITLE
🎈 Roadmap 7.5.0

### ISSUE THREAD

**Issue by kangarko** [kangarko/ChatControl-Pro#267]
![roadmap](https://i.imgur.com/a3FOfvL.png)
<h3><p align="center">A List of New Features and Ideas for the 7.5.0 release </p></h3>

## Want to suggest a feature?
* In order to stay high performance and to its original concept, please **only suggest features related to chat**. 
* If you have a feature request, please **open a new ticket**.

## What's Coming Next
The following features **will** be implemented in the next feature updates in the following order:
- [x] Spy-prefix when subscribed to a channel in spy mode.
- [x] Mute a channel and bypass with permission
- [x] Use interactive formats in handler alerts

## High priority
The following features have a high priority and are most likely to be implemented.

## Normal priority
The following features are to be considered to be implemented in my spare time and resources.

## Dropped
Features below were dropped but may come in the next release(s).
- Redis support. (I tried my best but haven't found an easy solution with the current way chat is handled.)
- Mail system. (Lack of time + there is already support for that in Essentials)
- Channels: channel require certain statistics f.x. how long player played (Lack of time.)

**Feel free to comment below, but comments are cleaned regularly to keep this page clean.**

**Comment by Rodrogamby** [comment]
Amazing! A mail system would be great ;)

**Comment by DuckCraftPvP** [comment]
any idea when this might be done?

**Comment by kangarko** [comment]
There's no ETA. I am moving soon and starting university. I'll get back to it parts by parts in holidays or the weekends.

**Comment by ghosts1234** [comment]
If faction support is added and released in around a week or two im going to instantly go for this plugin, problem is I have a server that has multiple game modes on one server (going to space out with bungee later on, which is another reason this plugin would work great as i wouldent need to configure a whole new plugin that supports bungee) and haveing the ability to make /rules and /help and other things like that have custom messages per worlds would work wonders. But one of the game modes is factions, so rip me I guess for the time being.

**Comment by kangarko** [comment]
The factions support is there. You can use the native {factions} variable to display the Factions name, or simple install PlaceholderAPI and use all placeholders from there.

What is above, is the relation placeholder. This is a special minor placeholder displaying how the player is being related to your faction (red, green, etc.).

**Comment by kangarko** [comment]
Much of the work has been done. The road-map has been cleaned. Unfortunately I had to drop and rearrange some features (that's for Autumn or even Christmas holidays :)).

**Comment by kangarko** [comment]
Features and basic testing are complete. Now we are testing inter-Bungee functionality and preparing the release.

**Comment by kangarko** [comment]
Released. Expecting safe landing, sir.
