### ISSUE TITLE
Roadmap 7.0.0

### ISSUE THREAD

**Issue by kangarko** [kangarko/ChatControl-Pro#42]
This is an up-to-date list of features to be considered and added in the 7.0.0 release. Not sorted by priority. Sidenote: Those are no promises.

## Rules
- [x] Operators `ignore world`, `then actionbar`, `then title` and `then bossbar` #10 and #39
   * Preserve third party plugin compatibility
- [x] Same system behind standard rules and packet rules, allowing all operators to be used in packet rules, plus the special ones.
- [x] Prevent joining players with vulgar nicknames.

## Messages
- [x] More bungee messages 
  - [x] Join / Quit / Kick messages over bungee
  - [x] Bungee server switch messages ("switched to {server_name}/ connected to this server)
- [x] World change and channel join/quit/spy(?) messages
- [x] Bungee support for private messaging
- [x] Socialspy command. Added as /spy 
- [x] Message of The Day #3
- [x] Death Messages #3
- [x] Connected worlds in ranged chat

## Developer
- [x] API #17 

## General
- [x] Interactive chat elements per permission, chat message remover (see #27). Added but with opposite logic due to the fact that message would need to be recompiled for every player in such case, performance would suffer.

**I usually do not remove comments, but they will be cleaned regularly to keep this page clean.**

**Comment by rErEaT** [comment]
What about private message spy? and private messages? :P

**Comment by kangarko** [comment]
Those are already in development. 

Here is only a list of features to be implemented in a far future release, or those of which development is not started yet.

**Comment by rErEaT** [comment]
oh, then waiting. :)

**Comment by NoHoPeLess** [comment]
Very good :D hope u release it fast :D like new stuff (bungee msg very important) :DDD greetz and thanks for all!

**Comment by kangarko** [comment]
Version 7.0.0 has scheduled release this week.

**Comment by kangarko** [comment]
Feature implementation complete. Major testing done. Release ETA: tonight

**Comment by kangarko** [comment]
Released.
