### ISSUE TITLE
🎈 Roadmap: Future Ideas

### ISSUE THREAD

**Issue by kangarko** [kangarko/ChatControl-Pro#64]
This is an up-to-date list of features to be considered and added in future release(s). Sidenote: Those are no promises.

## Features
- [ ] An option for staff to view plugin's logs.
- [ ] Silent message cancellation (display the message to the user himself but not others).
- [ ] Inviting others to channels. #63 
- [ ] Nicknames #43
- [ ] Splitting log files between day, week, month, year, or not at all
- [ ] External services to filter messages. See #30
- [ ] Bring back @prolong functionality as per [this](https://www.spigotmc.org/threads/are-you-a-regex-expert-help-get-my-premium-plugin-for-free.273986/#post-2673998) article.
- [ ] A report system (https://github.com/kangarko/ChatControl-Pro/issues/631)

## Suspended

Most of them due to time, priority and practical issues.
- A command to allow players choose the sound they want to be played when they're afk.
- Ability to list, search, edit, test or remove rules ingame.
- Rules multiple lines check.
- Event triggers change channels? e.g. gamemode/**world** changes -> player is put into spectator's channel.
- Timed Messages: permission-based and bungee support
- Bungee: chat clear/mute
- Interactive '/chatcontrol' and '/channel' commands.

**I usually do not remove comments, but they will be cleaned regularly to keep this page clean.**

**Comment by DuckCraftPvP** [comment]
Can you update placeholder api to support relation based placeholders like %rel_factions_relation_colour%%factions_faction_name% that were introduced in 2.8.0

It works on other plugins but it needs support added on here.

**Comment by kangarko** [comment]
This is already there but thanks for suggesting anyways!

**Comment by DuckCraftPvP** [comment]
it wont work though, I've tested it. It works with deluxe chat and them but i hate deluxe chat and i wana use urs :P 

{rel_factions_relation_colour}

**Comment by gaRt3n** [comment]
Custom Channels which users can create. With Password etc. like this here.
Settings will be stored in a MySQL oder Flatfile

http://prntscr.com/iqv5br

/channel create <name> [password]
/channel join <name> [password]
/channel write <name> <message> (for global just write !<message>
/channel info
/channel main <name>
/channel leave <name>

As Owner of Channel
/channel op <name> <playername>
/channel deop <name> <playername>
/channel kick <name> <playername>
/channel set <name> color=<colorname> or &6
/channel set <name> password=<password> none for no password
/channel delete <name>

**Comment by kangarko** [comment]
Merged into roadmap.
