### ISSUE TITLE
Roadmap 7.1.0

### ISSUE THREAD

**Issue by kangarko** [kangarko/ChatControl-Pro#65]
This is an continuously updated list of features to be considered and added in the 7.1.0 release. 
Sidenote: Those are no promises.

## Implemented
- [x] Ability to reply back to the console
- [x] MySQL: warn points
- [x] Spy command enabled by default for those with permission.
- [x] Hide bungee join, leave and switch messages.
- [x] bug in sound notify #134 

## Delayed
- Channels: Chat-ignorer
- {recipient} placeholder #68
- Timed Messages: permission-based and bungee support
- Bungee: chat clear/mute
- Interactive '/chatcontrol' and '/channel' commands.
- Rewrite formatter to display player's message differently for each player online. This makes a) faction relation color placeholder and b) /ignore command possible.

## Discarded
- /force command to force to run a command for player

**I usually do not remove comments, but they will be cleaned regularly to keep this page clean.**

**Comment by kangarko** [comment]
Work begun. First two features were added. I will be focusing on the features that have high priority.

**Comment by kangarko** [comment]
Features and basic testing are complete. Except a release tonight.
